### ISSUE TITLE
Package suggestion: SysIdentPy

### ISSUE THREAD

**Issue by wilsonrljr** [dylanhogg/awesome-python#16]
I'm the developer of SysIdentPy, a python package for nonlinear system identification and forecasting. I'd like to have it listed in the Time Series section if possible.

Github link: https://github.com/wilsonrljr/sysidentpy

Documentation: https://sysidentpy.org/

Please let me know if you need any other information about the package.

**Comment by dylanhogg** [comment]
Done and deployed. Thanks for your contribution!
