### ISSUE TITLE
Package suggestion: EOmaps

### ISSUE THREAD

**Issue by raphaelquast** [dylanhogg/awesome-python#17]
Hey, I'm the dev of EOmaps, a python package to visualize and analyze geographical datasets.
Would be nice if you could include it in the GIS section!

- Github: https://github.com/raphaelquast/EOmaps
- Docs: https://eomaps.readthedocs.io/en/latest/

**Comment by dylanhogg** [comment]
Done and included in the GIS category. Thanks for your contribution!
