### ISSUE TITLE
Package suggestion: Embedchain

### ISSUE THREAD

**Issue by taranjeet** [dylanhogg/awesome-python#20]
Hey, I'm the founder of Embedchain, an open-source RAG framework to create AI apps on top of your data.
Would be nice if you could include it in the "LLMs and ChatGPT" section.

Github: https://github.com/embedchain/embedchain
Docs: https://docs.embedchain.ai/

**Comment by dylanhogg** [comment]
Thanks for your suggestion, Embedchain looks like a great project and has been added.
