### ISSUE TITLE
Package suggestion: INSTLD

### ISSUE THREAD

**Issue by pomponchik** [dylanhogg/awesome-python#21]
Hi! I am the author of [`INSTLD`](https://github.com/pomponchik/instld), the simplest package management tool.

I suggest adding a new section "Package management" and adding this tool there.

Github: https://github.com/pomponchik/instld

**Comment by dylanhogg** [comment]
Thanks for your suggestion.

I've added it as a repo to crawl, however the stars and activity fall below a minimum threshold to be displayed. It looks like a growing project so will automatically be displayed in time.

An undocumented feature on the website is to add an "f" parameter to see all repos like this: https://www.awesomepython.org/?q=package-manager&f
