### ISSUE TITLE
add libs

### ISSUE THREAD

**Issue by Xaego** [dylanhogg/awesome-python#23]
Hi. cool list
may be you can add this few libs
physical optics: integrated modeling, phase retrieval, segmented systems, polynomials and fitting, sequential raytracing...
https://github.com/brandondube/prysm
Productive, portable, and performant GPU programming in Python.
https://github.com/taichi-dev/taichi

**Comment by dylanhogg** [comment]
These are fantastic suggestions, thanks. Now added to readme and deployed to www.awesomepython.org.

Do you have other suggestions you think could be included here?

**Comment by Xaego** [comment]
automated PC control. open source commercial project
https://www.pyopenrpa.ru/wiki/guide/v1.2.12_ENG/html/01_HowToInstall.html
Free Open Source Enterprise Grade RPA
https://github.com/open-rpa/openrpa
A Python package with bindings to the "Virtual Instrument Software Architecture" VISA library, in order to control measurement devices and test equipment via GPIB, RS232, or USB.
https://github.com/pyvisa/pyvisa
Python package for device control and experiment automation
https://github.com/AlexShkarin/pyLabLib
geometric ray tracing for optical systems
https://github.com/mjhoptics/ray-optics?tab=readme-ov-file
